title: Biopragmatics Stack
author: Charles Tapley Hoyt
email: cthoyt@gmail.com
description: >
  Software supporting biomedical semantics and pragmatics

minima:
  social_links:
    github: biopragmatics
    mastodon:
      - username: biopragmatics
        instance: fosstodon.org
  header_pages:
    - workshops

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

include:
  - ".well-known"
